apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resumebot
resources:
- namespace.yaml
- database.yaml
- app-sealed-secret.yaml
- kservice.yaml
- service-binding.yaml
- audit.yaml
